# Generated by Django 2.2.16 on 2022-08-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
    ]
