# Generated by Django 2.2.16 on 2022-08-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220808_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Пароль'),
        ),
    ]
