# Generated by Django 2.2.16 on 2022-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220808_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'administrator'), ('moderator', 'moderator'), ('user', 'user')], default='user', max_length=30, verbose_name='Роль'),
        ),
    ]
