# Generated by Django 2.2.16 on 2022-08-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220812_0027'),
        ('reviews', '0004_auto_20220812_1907'),
    ]

    operations = [
    ]
