# Generated by Django 2.2.16 on 2022-08-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_remove_comment_title'),
        ('reviews', '0017_auto_20220817_2101'),
    ]

    operations = [
    ]
